[package]
name = "seqproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky="0.9.2"
antisequence = { git = "https://github.com/Daniel-Liu-c0deb0t/ANTISEQUENCE/", branch='main' }