[package]
name = "seqproc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky="0.9.2"
argh="0.1.10"
antisequence = { git = "https://github.com/noahcape/ANTISEQUENCE/", branch='main' }