[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
blake3 = "1.8.7"
clap = { version = "4.4.8", features = ["derive"] }
seqproc-seqspec-import = { path = "../crates/seqproc-seqspec-import" }
seqproc = { path = ".." }
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
walkdir = "2.5"
