use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Component, Path, PathBuf},
    process::Command,
};

use clap::{Args, Parser, Subcommand};
use seqproc::execute::compile_geom_typed;
use seqproc_seqspec_import::{assess, ImportOptions, ImportStatus, IMPORTER_VERSION};
use serde::{Deserialize, Serialize};
use walkdir::WalkDir;

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Task,
}

#[derive(Subcommand)]
enum Task {
    /// Assess pinned official seqspec corpora and write JSON/CSV/Markdown reports.
    SeqspecCompat(CompatArgs),
}

#[derive(Args)]
struct CompatArgs {
    #[arg(long, default_value = "planning/seqspec-corpora.toml")]
    manifest: PathBuf,
    #[arg(long, default_value = "target/seqspec-corpora")]
    corpus_dir: PathBuf,
    #[arg(long, default_value = "planning/generated/seqspec-compat")]
    out: PathBuf,
    /// Clone/fetch corpora. Without this flag, the command is strictly offline.
    #[arg(long)]
    fetch: bool,
}

#[derive(Deserialize)]
struct Manifest {
    report_version: String,
    corpus: Vec<Corpus>,
}

#[derive(Deserialize)]
struct Corpus {
    name: String,
    repository: String,
    commit: String,
    path: String,
    sparse: Vec<String>,
    #[serde(default)]
    local_path: Option<PathBuf>,
}

#[derive(Debug, Serialize)]
struct Row {
    corpus: String,
    corpus_commit: String,
    specification: String,
    assay_id: String,
    modality: String,
    status: ImportStatus,
    generated_efgdl: bool,
    compiles: bool,
    compile_error: Option<String>,
    geometry_path: Option<String>,
    lane_count: usize,
    capability_blockers: Vec<String>,
    diagnostic_codes: Vec<String>,
    blocking_diagnostic_codes: Vec<String>,
}

#[derive(Serialize)]
struct Report {
    report_version: String,
    importer_version: String,
    manifest_digest: String,
    specifications: Vec<SpecificationRow>,
    rows: Vec<Row>,
    status_counts: BTreeMap<String, usize>,
    capability_impact: Vec<CapabilityImpact>,
}

#[derive(Debug, Serialize)]
struct SpecificationRow {
    corpus: String,
    corpus_commit: String,
    specification: String,
    assay_id: String,
    modality_count: usize,
    converted_modality_count: usize,
    cleanly_convertible: bool,
    partially_convertible: bool,
    requires_resource_binding: bool,
    statuses: Vec<String>,
    limitations: Vec<String>,
    geometry_paths: Vec<String>,
}

#[derive(Serialize)]
struct CapabilityImpact {
    capability: String,
    blocked_modalities: usize,
    blocked_specs: usize,
}

fn main() {
    let result = match Cli::parse().command {
        Task::SeqspecCompat(args) => compatibility_report(args),
    };
    if let Err(error) = result {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn compatibility_report(args: CompatArgs) -> Result<(), Box<dyn std::error::Error>> {
    let source = fs::read_to_string(&args.manifest)?;
    let manifest: Manifest = toml::from_str(&source)?;
    fs::create_dir_all(&args.out)?;
    let geometry_staging = tempfile::TempDir::new_in(&args.out)?;
    fs::write(
        geometry_staging.path().join(".seqproc-generated"),
        "Generated by `cargo run -p xtask -- seqspec-compat`; safe to replace.\n",
    )?;
    let mut rows = Vec::new();
    for corpus in &manifest.corpus {
        let root = materialize_corpus(corpus, &args.corpus_dir, args.fetch)?;
        let scan_root = root.join(&corpus.path);
        let entries = WalkDir::new(&scan_root)
            .follow_links(false)
            .into_iter()
            .filter_map(Result::ok)
            .filter(|entry| {
                let name = entry.file_name().to_string_lossy();
                entry.file_type().is_file() && (name == "spec.yaml" || name.ends_with(".spec.yaml"))
            })
            .collect::<Vec<_>>();
        if entries.is_empty() {
            return Err(format!(
                "corpus `{}` contains no seqspec YAML files under {}",
                corpus.name,
                scan_root.display()
            )
            .into());
        }
        for entry in entries {
            let yaml = fs::read_to_string(entry.path())?;
            let relative = entry
                .path()
                .strip_prefix(&root)
                .unwrap_or(entry.path())
                .display()
                .to_string();
            match assess(&yaml, &relative, &ImportOptions::default()) {
                Ok(assessment) => {
                    if assessment.geometries.is_empty() {
                        rows.push(empty_row(
                            corpus,
                            relative,
                            assessment.assay_id.unwrap_or_default(),
                            assessment
                                .diagnostics
                                .iter()
                                .map(|diagnostic| diagnostic.code.clone())
                                .collect(),
                        ));
                    } else {
                        for geometry in assessment.geometries {
                            let compile_result = (!geometry.efgdl.is_empty())
                                .then(|| compile_geom_typed(&geometry.efgdl));
                            let compiles = compile_result.as_ref().is_some_and(Result::is_ok);
                            let compile_error = compile_result
                                .and_then(Result::err)
                                .map(|error| format!("{error:?}"));
                            let diagnostics = assessment
                                .diagnostics
                                .iter()
                                .chain(&geometry.diagnostics)
                                .collect::<Vec<_>>();
                            let blocking_diagnostic_codes = diagnostics
                                .iter()
                                .filter(|diagnostic| {
                                    diagnostic.severity == seqproc_seqspec_import::Severity::Error
                                })
                                .map(|diagnostic| diagnostic.code.clone())
                                .collect::<BTreeSet<_>>()
                                .into_iter()
                                .collect();
                            let geometry_path = if compiles {
                                let relative_geometry = geometry_output_path(
                                    &corpus.name,
                                    &relative,
                                    &geometry.modality,
                                )?;
                                let staged_path = geometry_staging.path().join(&relative_geometry);
                                if let Some(parent) = staged_path.parent() {
                                    fs::create_dir_all(parent)?;
                                }
                                fs::write(&staged_path, &geometry.efgdl)?;
                                Some(
                                    Path::new("geometries")
                                        .join(relative_geometry)
                                        .to_string_lossy()
                                        .into_owned(),
                                )
                            } else {
                                None
                            };
                            rows.push(Row {
                                corpus: corpus.name.clone(),
                                corpus_commit: corpus.commit.clone(),
                                specification: relative.clone(),
                                assay_id: assessment.assay_id.clone().unwrap_or_default(),
                                modality: geometry.modality,
                                status: geometry.status,
                                generated_efgdl: !geometry.efgdl.is_empty(),
                                compiles,
                                compile_error,
                                geometry_path,
                                lane_count: geometry.inputs.len(),
                                capability_blockers: diagnostics
                                    .iter()
                                    .filter_map(|diagnostic| diagnostic.capability.clone())
                                    .collect::<BTreeSet<_>>()
                                    .into_iter()
                                    .collect(),
                                diagnostic_codes: diagnostics
                                    .iter()
                                    .map(|diagnostic| diagnostic.code.clone())
                                    .collect::<BTreeSet<_>>()
                                    .into_iter()
                                    .collect(),
                                blocking_diagnostic_codes,
                            });
                        }
                    }
                }
                Err(error) => rows.push(empty_row(
                    corpus,
                    relative,
                    String::new(),
                    vec![format!("yaml_parse:{error}")],
                )),
            }
        }
    }
    rows.sort_by(|left, right| {
        (&left.corpus, &left.specification, &left.modality).cmp(&(
            &right.corpus,
            &right.specification,
            &right.modality,
        ))
    });

    let mut status_counts = BTreeMap::new();
    let mut capability_modalities: BTreeMap<String, usize> = BTreeMap::new();
    let mut capability_specs: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for row in &rows {
        *status_counts
            .entry(format!("{:?}", row.status))
            .or_insert(0) += 1;
        if row.status != ImportStatus::BlockedSeqprocCapability {
            continue;
        }
        for capability in &row.capability_blockers {
            *capability_modalities.entry(capability.clone()).or_insert(0) += 1;
            capability_specs
                .entry(capability.clone())
                .or_default()
                .insert(format!("{}:{}", row.corpus, row.specification));
        }
    }
    let mut capability_impact = capability_modalities
        .into_iter()
        .map(|(capability, blocked_modalities)| CapabilityImpact {
            blocked_specs: capability_specs.get(&capability).map_or(0, BTreeSet::len),
            capability,
            blocked_modalities,
        })
        .collect::<Vec<_>>();
    capability_impact.sort_by(|left, right| {
        right
            .blocked_modalities
            .cmp(&left.blocked_modalities)
            .then_with(|| left.capability.cmp(&right.capability))
    });
    let specifications = summarize_specifications(&rows);
    let report = Report {
        report_version: manifest.report_version,
        importer_version: IMPORTER_VERSION.to_owned(),
        manifest_digest: format!("blake3:{}", blake3::hash(source.as_bytes()).to_hex()),
        specifications,
        rows,
        status_counts,
        capability_impact,
    };
    publish_geometry_tree(&args.out, geometry_staging)?;
    fs::write(
        args.out.join("report.json"),
        serde_json::to_vec_pretty(&report)?,
    )?;
    fs::write(args.out.join("report.csv"), render_csv(&report))?;
    fs::write(
        args.out.join("specifications.csv"),
        render_specifications_csv(&report),
    )?;
    fs::write(args.out.join("report.md"), render_markdown(&report))?;
    println!(
        "wrote {} specification rows and {} assessed modality rows to {}",
        report.specifications.len(),
        report.rows.len(),
        args.out.display()
    );
    Ok(())
}

fn empty_row(
    corpus: &Corpus,
    specification: String,
    assay_id: String,
    diagnostic_codes: Vec<String>,
) -> Row {
    Row {
        corpus: corpus.name.clone(),
        corpus_commit: corpus.commit.clone(),
        specification,
        assay_id,
        modality: String::new(),
        status: ImportStatus::BlockedSourceInvalid,
        generated_efgdl: false,
        compiles: false,
        compile_error: None,
        geometry_path: None,
        lane_count: 0,
        capability_blockers: Vec::new(),
        blocking_diagnostic_codes: diagnostic_codes.clone(),
        diagnostic_codes,
    }
}

fn summarize_specifications(rows: &[Row]) -> Vec<SpecificationRow> {
    let mut grouped = BTreeMap::<(&str, &str), Vec<&Row>>::new();
    for row in rows {
        grouped
            .entry((&row.corpus, &row.specification))
            .or_default()
            .push(row);
    }
    grouped
        .into_values()
        .map(|group| {
            let first = group[0];
            let modality_count = group.iter().filter(|row| !row.modality.is_empty()).count();
            let converted_modality_count = group
                .iter()
                .filter(|row| row.generated_efgdl && row.compiles)
                .count();
            let cleanly_convertible =
                !group.is_empty() && group.iter().all(|row| row.generated_efgdl && row.compiles);
            let mut limitations = BTreeSet::new();
            let mut statuses = BTreeSet::new();
            let mut geometry_paths = Vec::new();
            for row in &group {
                statuses.insert(format!("{:?}", row.status));
                if let Some(path) = &row.geometry_path {
                    geometry_paths.push(path.clone());
                }
                if row.generated_efgdl && !row.compiles {
                    limitations.insert("generated_efgdl_compile_failure".to_owned());
                }
                if !(row.generated_efgdl && row.compiles) {
                    limitations.extend(row.capability_blockers.iter().cloned());
                    limitations.extend(row.blocking_diagnostic_codes.iter().cloned());
                }
            }
            geometry_paths.sort();
            SpecificationRow {
                corpus: first.corpus.clone(),
                corpus_commit: first.corpus_commit.clone(),
                specification: first.specification.clone(),
                assay_id: first.assay_id.clone(),
                modality_count,
                converted_modality_count,
                cleanly_convertible,
                partially_convertible: converted_modality_count > 0 && !cleanly_convertible,
                requires_resource_binding: group
                    .iter()
                    .any(|row| row.status == ImportStatus::SupportedRequiresBinding),
                statuses: statuses.into_iter().collect(),
                limitations: limitations.into_iter().collect(),
                geometry_paths,
            }
        })
        .collect()
}

fn materialize_corpus(
    corpus: &Corpus,
    corpus_dir: &Path,
    fetch: bool,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    if let Some(local) = &corpus.local_path {
        return Ok(local.clone());
    }
    let root = corpus_dir.join(&corpus.name);
    if !root.join(".git").exists() {
        if !fetch {
            return Err(format!(
                "corpus `{}` is absent at {}; rerun with --fetch",
                corpus.name,
                root.display()
            )
            .into());
        }
        fs::create_dir_all(corpus_dir)?;
        checked(
            Command::new("git")
                .args([
                    "clone",
                    "--filter=blob:none",
                    "--no-checkout",
                    &corpus.repository,
                ])
                .arg(&root),
        )?;
    }
    if fetch {
        checked(Command::new("git").arg("-C").arg(&root).args([
            "fetch",
            "origin",
            &corpus.commit,
        ]))?;
    }
    if fetch {
        checked(
            Command::new("git")
                .arg("-C")
                .arg(&root)
                .args(["sparse-checkout", "set", "--no-cone"])
                .args(&corpus.sparse),
        )?;
        checked(Command::new("git").arg("-C").arg(&root).args([
            "checkout",
            "--detach",
            &corpus.commit,
        ]))?;
    }
    let current = checked_output(
        Command::new("git")
            .arg("-C")
            .arg(&root)
            .args(["rev-parse", "HEAD"]),
    )?;
    if current.trim() != corpus.commit {
        return Err(format!(
            "corpus `{}` is at {}, expected {}; rerun with --fetch",
            corpus.name,
            current.trim(),
            corpus.commit
        )
        .into());
    }
    Ok(root)
}

fn checked(command: &mut Command) -> Result<(), Box<dyn std::error::Error>> {
    let status = command.status()?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("command failed with {status}: {command:?}").into())
    }
}

fn checked_output(command: &mut Command) -> Result<String, Box<dyn std::error::Error>> {
    let output = command.output()?;
    if !output.status.success() {
        return Err(format!("command failed with {}: {command:?}", output.status).into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn csv_cell(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

fn render_csv(report: &Report) -> String {
    let mut output = String::from("corpus,commit,specification,assay_id,modality,status,generated_efgdl,compiles,compile_error,geometry_path,lane_count,capability_blockers,diagnostic_codes,blocking_diagnostic_codes\n");
    for row in &report.rows {
        output.push_str(&format!(
            "{},{},{},{},{},{:?},{},{},{},{},{},{},{},{}\n",
            csv_cell(&row.corpus),
            csv_cell(&row.corpus_commit),
            csv_cell(&row.specification),
            csv_cell(&row.assay_id),
            csv_cell(&row.modality),
            row.status,
            row.generated_efgdl,
            row.compiles,
            csv_cell(row.compile_error.as_deref().unwrap_or("")),
            csv_cell(row.geometry_path.as_deref().unwrap_or("")),
            row.lane_count,
            csv_cell(&row.capability_blockers.join(";")),
            csv_cell(&row.diagnostic_codes.join(";")),
            csv_cell(&row.blocking_diagnostic_codes.join(";"))
        ));
    }
    output
}

fn render_specifications_csv(report: &Report) -> String {
    let mut output = String::from("corpus,commit,specification,assay_id,modality_count,converted_modality_count,cleanly_convertible,partially_convertible,requires_resource_binding,statuses,limitations,geometry_paths\n");
    for row in &report.specifications {
        output.push_str(&format!(
            "{},{},{},{},{},{},{},{},{},{},{},{}\n",
            csv_cell(&row.corpus),
            csv_cell(&row.corpus_commit),
            csv_cell(&row.specification),
            csv_cell(&row.assay_id),
            row.modality_count,
            row.converted_modality_count,
            row.cleanly_convertible,
            row.partially_convertible,
            row.requires_resource_binding,
            csv_cell(&row.statuses.join(";")),
            csv_cell(&row.limitations.join(";")),
            csv_cell(&row.geometry_paths.join(";"))
        ));
    }
    output
}

fn render_markdown(report: &Report) -> String {
    let supported = report
        .rows
        .iter()
        .filter(|row| row.status.generated() && row.compiles)
        .count();
    let mut output = format!(
        "# seqspec compatibility report\n\nAssessed **{}** seqspec documents containing **{}** modality projections; **{}** projections generated EFGDL 2 that compiles. The specification matrix has exactly one row per source document. Capability impact is a conservative lower bound: rows requiring explicit read/modality policy are not guessed or attributed to a later capability.\n\n## Status summary\n\n| Status | Modalities |\n| --- | ---: |\n",
        report.specifications.len(), report.rows.len(), supported
    );
    for (status, count) in &report.status_counts {
        output.push_str(&format!("| `{status}` | {count} |\n"));
    }
    output.push_str(&format!(
        "\nManifest digest: `{}`; importer version: `{}`.\n\n## Corpus provenance\n\n| Corpus | Commit | Specifications | Modality rows |\n| --- | --- | ---: | ---: |\n",
        report.manifest_digest, report.importer_version
    ));
    let mut corpora = BTreeMap::<(&str, &str), (usize, usize)>::new();
    for row in &report.rows {
        corpora
            .entry((row.corpus.as_str(), row.corpus_commit.as_str()))
            .or_default()
            .1 += 1;
    }
    for row in &report.specifications {
        corpora
            .entry((row.corpus.as_str(), row.corpus_commit.as_str()))
            .or_default()
            .0 += 1;
    }
    for ((corpus, commit), (specifications, modalities)) in corpora {
        output.push_str(&format!(
            "| {corpus} | `{commit}` | {specifications} | {modalities} |\n"
        ));
    }
    output.push_str("\n## Capability impact\n\n| Rank | Missing capability | Blocked modalities | Blocked specs |\n| ---: | --- | ---: | ---: |\n");
    for (index, impact) in report.capability_impact.iter().enumerate() {
        output.push_str(&format!(
            "| {} | `{}` | {} | {} |\n",
            index + 1,
            impact.capability,
            impact.blocked_modalities,
            impact.blocked_specs
        ));
    }
    output.push_str("\n## Specification matrix\n\nA specification is cleanly convertible only when every declared modality projection converts and compiles. Resource bindings are reported separately because an external onlist is an expected input, not a conversion failure.\n\n| Corpus | Specification | Assay | Clean conversion | Converted modalities | Resource binding | Limitations |\n| --- | --- | --- | --- | ---: | --- | --- |\n");
    for row in &report.specifications {
        let outcome = if row.cleanly_convertible {
            "yes"
        } else if row.partially_convertible {
            "partial"
        } else {
            "no"
        };
        let limitations = if row.limitations.is_empty() {
            "\u{2014}".to_owned()
        } else {
            row.limitations
                .iter()
                .map(|limitation| format!("`{limitation}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        output.push_str(&format!(
            "| {} | `{}` | {} | {} | {}/{} | {} | {} |\n",
            row.corpus,
            row.specification,
            row.assay_id,
            outcome,
            row.converted_modality_count,
            row.modality_count,
            if row.requires_resource_binding {
                "required"
            } else {
                "none"
            },
            limitations
        ));
    }
    output.push_str("\n## Modality matrix\n\n| Corpus | Specification | Modality | Status | Lanes | Converted EFGDL | Required capability/action |\n| --- | --- | --- | --- | ---: | --- | --- |\n");
    for row in &report.rows {
        let action = if row.capability_blockers.is_empty() {
            row.diagnostic_codes.join(", ")
        } else {
            row.capability_blockers.join(", ")
        };
        let geometry = row
            .geometry_path
            .as_ref()
            .map_or_else(|| "no".to_owned(), |path| format!("[view]({path})"));
        output.push_str(&format!(
            "| {} | `{}` | {} | `{:?}` | {} | {} | {} |\n",
            row.corpus,
            row.specification,
            row.modality,
            row.status,
            row.lane_count,
            geometry,
            action
        ));
    }
    output
}

fn geometry_output_path(
    corpus: &str,
    specification: &str,
    modality: &str,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let mut output = PathBuf::from(safe_component(corpus));
    let specification = Path::new(specification);
    for component in specification.components() {
        match component {
            Component::Normal(value) => output.push(safe_component(&value.to_string_lossy())),
            Component::CurDir => {}
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(format!(
                    "refusing unsafe corpus-relative specification path `{}`",
                    specification.display()
                )
                .into())
            }
        }
    }
    let source_name = output
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("spec");
    output.set_file_name(format!("{source_name}.d"));
    output.push(format!("{}.geom", safe_component(modality)));
    Ok(output)
}

fn safe_component(value: &str) -> String {
    if value.is_empty() {
        return "_empty".to_owned();
    }
    let mut output = String::new();
    for byte in value.as_bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.') {
            output.push(char::from(*byte));
        } else {
            output.push_str(&format!("~{byte:02x}"));
        }
    }
    output
}

fn publish_geometry_tree(
    output_dir: &Path,
    staging: tempfile::TempDir,
) -> Result<(), Box<dyn std::error::Error>> {
    let destination = output_dir.join("geometries");
    if destination.exists() {
        let metadata = fs::symlink_metadata(&destination)?;
        if metadata.file_type().is_symlink() || !destination.join(".seqproc-generated").is_file() {
            return Err(format!(
                "refusing to replace unowned geometry output `{}`",
                destination.display()
            )
            .into());
        }
        fs::remove_dir_all(&destination)?;
    }
    fs::rename(staging.path(), &destination)?;
    let _published = staging.keep();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_row(
        specification: &str,
        modality: &str,
        status: ImportStatus,
        generated: bool,
        capability: &[&str],
        blocking: &[&str],
    ) -> Row {
        Row {
            corpus: "corpus".to_owned(),
            corpus_commit: "012345".to_owned(),
            specification: specification.to_owned(),
            assay_id: "assay".to_owned(),
            modality: modality.to_owned(),
            status,
            generated_efgdl: generated,
            compiles: generated,
            compile_error: None,
            geometry_path: generated.then(|| format!("geometries/{modality}.geom")),
            lane_count: 1,
            capability_blockers: capability.iter().map(|value| (*value).to_owned()).collect(),
            diagnostic_codes: blocking.iter().map(|value| (*value).to_owned()).collect(),
            blocking_diagnostic_codes: blocking.iter().map(|value| (*value).to_owned()).collect(),
        }
    }

    #[test]
    fn geometry_paths_preserve_corpus_specification_and_modality() {
        assert_eq!(
            geometry_output_path("igvf-seqspec", "specs/10x_atac/spec.yaml", "atac").unwrap(),
            PathBuf::from("igvf-seqspec/specs/10x_atac/spec.yaml.d/atac.geom")
        );
        assert_eq!(
            geometry_output_path("corpus", "assays/example.spec.yaml", "RNA + ATAC").unwrap(),
            PathBuf::from("corpus/assays/example.spec.yaml.d/RNA~20~2b~20ATAC.geom")
        );
    }

    #[test]
    fn geometry_paths_reject_parent_traversal() {
        assert!(geometry_output_path("corpus", "../outside.yaml", "rna").is_err());
    }

    #[test]
    fn specification_summary_has_one_row_per_source_and_unions_limitations() {
        let rows = vec![
            test_row("one.yaml", "rna", ImportStatus::Supported, true, &[], &[]),
            test_row(
                "one.yaml",
                "atac",
                ImportStatus::BlockedSeqprocCapability,
                false,
                &["partial_onlist_window_matching"],
                &["read_window_spans_regions"],
            ),
            test_row(
                "two.yaml",
                "rna",
                ImportStatus::SupportedRequiresBinding,
                true,
                &[],
                &[],
            ),
        ];
        let specifications = summarize_specifications(&rows);
        assert_eq!(specifications.len(), 2);
        assert!(specifications[0].partially_convertible);
        assert_eq!(specifications[0].converted_modality_count, 1);
        assert_eq!(specifications[0].modality_count, 2);
        assert_eq!(
            specifications[0].limitations,
            [
                "partial_onlist_window_matching".to_owned(),
                "read_window_spans_regions".to_owned()
            ]
        );
        assert!(specifications[1].cleanly_convertible);
        assert!(specifications[1].requires_resource_binding);
    }

    #[test]
    fn geometry_publication_replaces_only_an_owned_tree() {
        let output = tempfile::tempdir().unwrap();
        let destination = output.path().join("geometries");
        fs::create_dir(&destination).unwrap();
        fs::write(destination.join("user-file"), "keep").unwrap();
        let unowned_stage = tempfile::TempDir::new_in(output.path()).unwrap();
        assert!(publish_geometry_tree(output.path(), unowned_stage).is_err());
        assert!(destination.join("user-file").is_file());

        fs::write(destination.join(".seqproc-generated"), "owned").unwrap();
        let owned_stage = tempfile::TempDir::new_in(output.path()).unwrap();
        fs::write(owned_stage.path().join(".seqproc-generated"), "owned").unwrap();
        fs::write(owned_stage.path().join("new.geom"), "header { efgdl = 2 }").unwrap();
        publish_geometry_tree(output.path(), owned_stage).unwrap();
        assert!(!destination.join("user-file").exists());
        assert!(destination.join("new.geom").is_file());
    }
}
